### PR TITLE
improve the render of javascript that's inlined onto pages.

### PR DESCRIPTION
**Pull request by rg-3**
I found the previous code hard to edit and read, I think this
approach is easier to read and edit, especially if we want
to cover other properties or interpolate other values.

### CODE REVIEW

**Comment by srgl** [comment]
Agree! Just wanted to save a few cpu cycles, cause this runs on every page load.

**Comment by srgl** [comment]
@rg-3 Please replace arrow function with plain functions to support old chrome versions.

**Comment by rg-3** [comment]
@srgl Updated [here](https://github.com/srgl/ua-smart-switcher/commit/1e24f71ecfa409d55719d0bd81c19ca0e5307cfd), let me know if it is good and I can rebase down to one commit.

**Comment by srgl** [comment]
@rg-3 looks good to me

**Comment by rg-3** [comment]
@srgl Rebased.

**Pull request merged**
